version: "3"

services:
  # shops-service:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   environment:
  #     DSN: "host=postgres port=5402 user=postgres password=password dbname=shops sslmode=disable timezone=UTC connect_timeout=5"
  #   depends_on:
  #     - postgres

  postgres:
    image: "postgres:14.2"
    ports:
      - "5402:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shops
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
