// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	DeleteMenuItem(ctx context.Context, id int64) error
	DeleteShop(ctx context.Context, arg DeleteShopParams) error
	GetMenuItem(ctx context.Context, id int64) (MenuItem, error)
	GetShop(ctx context.Context, id int64) (Shop, error)
	GetShopsAdmin(ctx context.Context, userID int64) ([]Shop, error)
	ListMenuItems(ctx context.Context, shopID int64) ([]MenuItem, error)
	ListShops(ctx context.Context, arg ListShopsParams) ([]Shop, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
